In [1]:
import numpy as np

### 1. Создать массив из 25 нулей

In [2]:
a1 = [0 for i in range(25)]
a1

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [3]:
a1 = np.zeros(12)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 2. Создать массив из 10 единиц +

In [4]:
a2 = [1 for i in range(10)]
a2

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [5]:
a2 = np.ones(12)
a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 3. Создать массив из 12 пятерок +

In [6]:
a3 = [5 for i in range(12)]
a3

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [7]:
a3 = np.full(12, 5)
a3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### 4. Создать массив из целых чисел от 12 до 51 +

In [8]:
a4 = [i for i in range(12, 52)]
a4

[12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51]

In [9]:
a4 = np.arange(12, 52)
a4

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51])

### 5. Создать массив из целых четных чисел от 12 до 51 + 

In [10]:
a5 = [i for i in range(12, 52, 2)]
a5

[12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

In [11]:
a5 = np.arange(12, 52, 2)
a5

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50])

### 6. Создать матрицу 3х3 с числами от 1 до 9 + 

In [12]:
a6 = [[i for i in range(1, 4)], [i for i in range (4, 7)], [i for i in range(7, 10)]]
a6

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
a6 = np.arange(1, 10).reshape(3, 3)
a6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 7. Создать единичную матрицу 5х5 + 

In [14]:
a7 = [[1 for i in range(5)] for i in range(5)]
a7

[[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]]

In [15]:
a7 = np.ones((5,5))
a7

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 8. Создайте матрицу 

In [16]:
a8 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
a8

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### 9. Создайте матрицу 

In [17]:
a9 = np.arange(1, 26).reshape(5, 5)
a9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 10. Извлечь подматрицу из 9 задания

In [18]:
a10 = a9[2:, 1:]
a10

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

### 11. Написать код, который извлечет число 15 из 9 задания +

In [19]:
a11 = a9[2][4]
a11

15

In [20]:
a11 = a9[2,4]
a11

15

### 12. Извлечь из 9 задания матрицу +

In [21]:
a12 = a9[1:4, 1:2]
a12

array([[ 7],
       [12],
       [17]])

In [22]:
a12 = a9[1:4, [1]]
a12

array([[ 7],
       [12],
       [17]])

### 13. Извлечь из 9 задания строку +
[[21 22 23 24 25]]

In [23]:
a13 = a9[4:]
a13

array([[21, 22, 23, 24, 25]])

### 14. Извлечь две строки из 9 задания +

In [24]:
a14 = a9[3:, :]
a14

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 15. Получить сумму всех значений из матрицы в задании 9 +

In [25]:
a15 = a9.sum()
a15

325

In [26]:
a15 = np.sum(a9)
a15

325

### 16. Получить сумму значений в колонках из матрицы в задании 9 +

In [27]:
a16 = [sum(col) for col in zip(*a9)]
a16

[55, 60, 65, 70, 75]

In [28]:
a16 = np.sum(a9, axis=0)
a16

array([55, 60, 65, 70, 75])